### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSSS1980** [omparay/AppleChallenge#1]
MY FRIEND PLEASEEEEEEEE CAN YOU MAKE A WEB VERSION?I HAVE NO IDEA FROM DEVELOPING AND I DONT KNOW HOW TO DO IT!!!I AM BEGGING YOU MAN

**Comment by omparay** [comment]
Who are you? 
And what exactly are you asking for? 
Did you want me to document this in a separate web page? 
Or did you want me to make this app as a web version?

If you do want a web version of the app you are out of luck. I don't do web-apps or web services anymore. For the last 10 years I have only been a native iOS dev and I have no wish to go back and develop webapps or web services again. I can use DreamFactory (https://www.dreamfactory.com/) for those.

If you need to learn iOS development I suggest:
https://www.raywenderlich.com/
https://developer.apple.com/videos/wwdc2019/

Also:
https://www.youtube.com/user/ENGLISHCLASS101

> MY FRIEND PLEASEEEEEEEE CAN YOU MAKE A WEB VERSION?I HAVE NO IDEA FROM DEVELOPING AND I DONT KNOW HOW TO DO IT!!!I AM BEGGING YOU MAN
